# 开发环境配置
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  influxdb3-core:
    url: "http://localhost:8181"
    database: "monitor"
    token: "apiv3_p3Y4ojB3vTLwJaaUiI40NXUQQ5bnfjxE1iBoMBoJyO-quZCiLG6pTPXvvMfX1xHe-Dzr3brMTDiniGjvK29k5A"
  mail:
    host: smtp.163.com
    username: jxlpdt1@163.com
    password: SYU3KgKB4QeLcn5M
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
#    listener:
#      simple:
#        auto-startup: false
  datasource:
    url: jdbc:mysql://localhost:3306/monitor
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 5
      limit: 100
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  minio:
    endpoint: 'http://localhost:9000'
    username: 'minioadmin'
    password: 'minioadmin'
  data:
    redis:
#      port: 6449
      host: localhost
      port: 6379